# Generated by Django 4.1.7 on 2023-05-03 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=100)),
                ('sender_customer_id', models.IntegerField(null=True)),
                ('sender_first_name', models.CharField(max_length=50)),
                ('sender_last_name', models.CharField(max_length=40)),
                ('sender_address', models.CharField(max_length=250)),
                ('sender_phone', models.CharField(max_length=11)),
                ('reciever_customer_id', models.IntegerField(null=True)),
                ('reciever_first_name', models.CharField(max_length=50)),
                ('reciever_last_name', models.CharField(max_length=40)),
                ('reciever_address', models.CharField(max_length=250)),
                ('reciever_phone', models.CharField(max_length=11)),
                ('cargo_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_feature', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_edt', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('courier_name', models.CharField(max_length=80)),
                ('cargo_limit', models.IntegerField(null=True)),
                ('active_cargo_count', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('role', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
