# Generated by Django 4.1.7 on 2023-05-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=40)),
            ],
        ),
    ]
