# Generated by Django 4.1.7 on 2023-05-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_tracking', '0002_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='courier_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
