# Generated by Django 4.1.7 on 2023-05-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_tracking', '0003_cargo_courier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='reciever_city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='sender_city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
